import { documents, news } from "@/data/site-content";
import { Card, Container, PageHero } from "./UI";
import Image from "next/image";

export function NewsPage() {
  return <><PageHero title="Les actualités de l’EDR Nord Toulousain" text="Les informations, rendez-vous et documents utiles de l’école de rugby." /><Container className="py-16">
    <section aria-labelledby="registration-title" className="rounded-3xl border-2 border-red bg-white p-6 shadow-card sm:p-10">
      <p className="text-sm font-black uppercase tracking-[.18em] text-red">Saison 2026-2027</p><h2 id="registration-title" className="mt-2 text-3xl font-black text-night sm:text-4xl">Inscriptions à l’EDR Nord Toulousain</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">Retrouvez ici le dossier nécessaire pour préparer l’inscription de votre enfant à l’École de Rugby Nord Toulousain.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href={documents.registration.path} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-full bg-red px-6 py-3 text-center font-bold text-white hover:bg-coral">Consulter le dossier d’inscription<span className="sr-only"> (nouvel onglet)</span></a><a href={documents.registration.path} download className="inline-flex min-h-12 items-center justify-center rounded-full bg-blue px-6 py-3 text-center font-bold text-white hover:bg-night">Télécharger le dossier</a></div><p className="mt-4 text-sm text-slate-500">{documents.registration.title} · Document Word</p>
    </section>
    <div className="mt-12 grid gap-7 lg:grid-cols-2">{news.map((item) => <Card key={item.path} className="overflow-hidden p-0"><a href={item.path} target="_blank" rel="noopener noreferrer" className="block bg-night"><Image src={item.path} alt={item.alt} width={1024} height={1536} sizes="(min-width: 1024px) 50vw, 100vw" className="aspect-[2/3] h-auto w-full object-contain" /></a><div className="p-6"><h2 className="text-2xl font-black text-night">{item.title}</h2><p className="mt-3 leading-7 text-slate-600">{item.description}</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><a href={item.path} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-full bg-blue px-5 py-3 text-center font-bold text-white hover:bg-night">Consulter le document<span className="sr-only"> (nouvel onglet)</span></a><a href={item.path} download className="inline-flex min-h-12 items-center justify-center rounded-full border-2 border-blue px-5 py-3 text-center font-bold text-blue hover:bg-blue hover:text-white">Télécharger le visuel</a></div></div></Card>)}</div>
  </Container></>;
}
